la
LiliyanAV/caesar pull request #1
Opened 2021-05-07 14:52 UTC by Luchia04

2021-05-07 15:34 UTC, HarIgo23 requested changes

2021-05-07 15:34 UTC, HarIgo23 commented on main.py
> +        return Caesar.crypt(self, encoded_text)
You should use self, not class name. Rewrite

2021-05-07 15:34 UTC, HarIgo23 commented on main.py
> +        self.size = ord('z') - ord('a')+1
You have to add space between operator

2021-05-07 15:34 UTC, HarIgo23 commented on main.py
> +        return "".join([self.crypt_chr(chr) for chr in text])
You don't handle special symbols, spaces and snother.

2021-05-07 15:34 UTC, HarIgo23 commented on test.py
> +import unittest
Use pytest for testing

2021-05-07 15:34 UTC, HarIgo23 commented on test.py
> +        self.assertEqual(self.p.crypt("aha"), "nun")
There are useless test. You should check all alphabet in asc and desc order + maybe some random phrase with special symbols, space and uppercase letter.

2021-06-01 10:40 UTC, HarIgo23 requested changes
You forgot to add Readme file you write instructions how set up you project on computer.

2021-06-01 10:40 UTC, HarIgo23 commented on .pre-commit-config.yaml
> +    hooks:
add flake8 to precommit

2021-06-01 10:40 UTC, HarIgo23 commented on .gitignore
> +/python-vitual-environments/
Add venv/ and env/ in .gitignore

2021-06-01 10:40 UTC, HarIgo23 commented on main.py
> +    def __init__(self):
Use shift  argument with default value as 13

2021-06-01 10:40 UTC, HarIgo23 commented on main.py
> +        self.shift = 13
Use argument to set up value

2021-06-01 10:40 UTC, HarIgo23 commented on main.py
> +        self.alpha = [chr(x) for x in range(ord('a'), ord('z') + 1)]
alphabet

2021-06-01 10:40 UTC, HarIgo23 commented on main.py
> +        self.size = ord('z') - ord('a') + 1
len(self.alphabet)

2021-06-01 10:40 UTC, HarIgo23 commented on main.py
> +       return chr((ord(ch) - ord('a') + self.shift) % self.size + ord('a')) if ch in self.alpha else ch
Rewrite as
`
if ch in self.alpha:
    return chr((ord(ch) - ord('a') + self.shift) % self.size + ord('a'))
return ch 
`
, it's too complicated expression for one line

2021-06-01 10:40 UTC, HarIgo23 commented on requirements.txt
> +attrs==21.2.0
Where are pre-commit and pytest?

2021-06-01 10:40 UTC, HarIgo23 commented on test_main.py
> +from main import Caesar
https://www.python.org/dev/peps/pep-0008/#imports
Imports should be grouped in the following order:

1. Standard library imports.
2. Related third party imports.
3. Local application/library specific imports.

2021-06-01 10:40 UTC, HarIgo23 commented on test_main.py
> +from main import Caesar
'
import pytest

from main import Caesar
'
You should write it this way, bcs pytest - third party imports, main - local application imports.

2021-06-01 10:40 UTC, HarIgo23 commented on test_main.py
> +    assert c.crypt("b arf") == "o nes"
Add more test with cpecific symbols.

2021-06-14 15:20 UTC, HarIgo23 requested changes

2021-06-14 15:20 UTC, HarIgo23 commented on .gitignore
> +/env/env/
What is it?

2021-06-14 15:20 UTC, HarIgo23 commented on README.md
> +> :arrow_right: git clone https://github.com/Luchia04/caesar.git
Change to
git clone https://github.com/Luchia04/caesar.git caesar
cd caesar

and delete first two command where you create and move into directory

2021-06-14 15:20 UTC, HarIgo23 commented on README.md
> +> :arrow_right: pip install --upgrade pip
No need this command

2021-06-14 15:20 UTC, HarIgo23 commented on README.md
> +> :arrow_right: flake8 main.py
Where chapter with instruction how run your app?

2021-06-14 15:20 UTC, HarIgo23 commented on main.py
> +    #  return (
Delete unused code

2021-06-14 15:20 UTC, HarIgo23 commented on requirements.txt
> +attrs==21.2.0
Use pip freeze > requirements.txt to write into file all dependences

2021-06-14 15:20 UTC, HarIgo23 commented on test_main.py
> +    assert c.crypt("b arf") == "o nes"
You didn't resolve this problem. You need add more TEST CASES in TESTS file.

2021-06-14 15:20 UTC, HarIgo23 commented on test_main.py
> +from main import Caesar
Why you remove pytest. You need change order. NOT delete this import.

2021-06-15 09:55 UTC, Luchia04 commented on test_main.py
> +from main import Caesar
I can't pushing this order test_main.py:2:1: F401 'pytest' imported but unused

2021-06-15 10:08 UTC, Luchia04 commented on .gitignore
> +/env/env/
It is .gitignore

2021-06-15 13:03 UTC, HarIgo23 requested changes

2021-06-16 07:59 UTC, HarIgo23 approved these changes

2021-07-21 13:23 UTC, merged